services:
  spark-master:
    image: "docker.io/knoguchi22/spark-rapids-launchables-demo:latest"
    container_name: spark-master
    hostname: spark-master
    user: spark
    environment:
      - SPARK_HOME=/opt/spark
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "8080:8080"
    command: ["/opt/spark/sbin/start-master.sh"]
    volumes: 
      - sparkvol:/opt/spark
  spark-worker:
    image: "docker.io/knoguchi22/spark-rapids-launchables-demo:latest"
    container_name: spark-worker
    hostname: spark-worker
    user: spark
    environment:
      - SPARK_HOME=/opt/spark
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "8081:8081"
    command: ["/opt/spark/sbin/start-worker.sh"]
    volumes: 
      - sparkvol:/opt/spark
  spark-history-server:
    image: "docker.io/knoguchi22/spark-rapids-launchables-demo:latest"
    container_name: spark-history-server
    hostname: spark-history-server
    user: spark
    environment:
      - SPARK_HOME=/opt/spark
    ports:
      - "18080:18080"
    command: ["/opt/spark/sbin/start-history-server.sh"]
    volumes: 
      - sparkvol:/opt/spark
  jupyter:
    image: "docker.io/knoguchi22/spark-rapids-launchables-demo:latest"
    container_name: jupyter
    hostname: jupyter
    user: spark
    environment:
      - SPARK_HOME=/opt/spark
    ports:
      - "8888:8888"
    command: ["/usr/local/bin/jupyter", "notebook"]
    volumes: 
      - sparkvol:/opt/spark

volumes: 
  sparkvol:
